#!/usr/bin/env bash
# A fontforge autotrace script for vectorizing bitmap fonts.

# This script is designed for use with fontforge, see:
# http://monsterfacegames.blogspot.com/2013/10/creating-pixel-font-for-your-game.html
# https://stackoverflow.com/questions/3750124/how-to-convert-a-bitmap-font-fon-into-a-truetype-font-ttf/8350648

# Script was based on:
# https://gist.github.com/bendmorris/7170209
# ... but reduces filter radius, which I found gives better results.

argv=("$0" "$@")
last=${argv[$#]}
startwidth=$(identify -format "%w" -- "$last")
startheight=$(identify -format "%h" -- "$last")
newwidth=$(( $startwidth * 40))
newheight=$(( $startheight * 40))
cat "$last" |
    mkbitmap -f 3 -s 1 |
    convert -scale "${newwidth}x${newheight}" - - |
    /usr/bin/potrace \
        --turdsize 0 \
        --opttolerance 0 \
        -a 0 \
        "${argv[@]:1:$#-1}" \
        -r 2880
